### ISSUE TITLE
AFNetworking 3.x migration

### ISSUE THREAD

**Issue by hyunwoo3008** [AFNetworking/AFJSONRPCClient#23]
AFNetworking 3.x migration please

**Comment by abbasmousavi** [comment]
You can use the code in this pull request https://github.com/AFNetworking/AFJSONRPCClient/pull/22, that has not merged yet.

**Comment by hyunwoo3008** [comment]
thanks abbasmousavi !!
but This code has a problem in my project 

120lines (request failed and 'AFNetworking', '~> 3.1' is deprecated )

[self POST:@"" parameters:payload success:^(NSURLSessionDataTask \* _Nonnull task, id  _Nonnull responseObject)

EDIT CODE ( .. 
[self POST:**[self.endpointURL absoluteString]** parameters:payload **progress:^(NSProgress \* _Nonnull uploadProgress) { }** success:^(NSURLSessionDataTask \* _Nonnull task, id  _Nullable responseObject)

thanks have a good day
