### ISSUE TITLE
Version control marker in file

### ISSUE THREAD

**Issue by ypeskin** [AFNetworking/AFJSONRPCClient#4]
Hello,
Just updated to the latest version AFJSONRPCClient (0.4.0) and thought that you should know that there is an issue in the source code.
1. Error: Version control marker in file. In AFJSONRPCClient.h you have the following:
<<<<<<< HEAD
# \- (id)proxyWithProtocol:(Protocol *)protocol;
- (NSMutableURLRequest *)requestWithMethod:(NSString *)method
                              parameters:(id)parameters
                               requestId:(id)requestId;

> > > > > > > 795eff039dbde4048fcfe195f9b1697a3498b477

Thanks,
Yury

**Comment by boecko** [comment]
me too!...
BTW: I did mention that already ;) https://github.com/AFNetworking/AFJSONRPCClient/pull/3#issuecomment-17414252

**Comment by kenmaz** [comment]
me too

**Comment by mattt** [comment]
Looks like a few wires got crossed in that last merge. Only saw the problem just now. 1a8aa5722be87e0ca0aa43ebab8233e1ee5c5ac5 resolves this and resets the 0.4.0 tag.
